
site_name: Zero to Mastery Learn Machine Learning and Deep Learning Concepts
site_url: 
site_description: Learn important machine learning concepts hands-on by writing PyTorch code.

repo_url: https://github.com/anas1IA-art/site
repo_name: anas1IA-art/ML-DL-Concepts

docs_dir: docs

theme:
  name: material
  features:
    - navigation.top
    - navigation.tabs
  palette:
    primary: black

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences


  
plugins:
 - mkdocs-jupyter:
    include_source: True
 - search
 # - social

edit_uri: ""

site_author: ANAS NOURI

nav:
  - Home: 'index.md'

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/moussa-jamor-b17a58253/
    - icon: fontawesome/brands/github
      link: https://github.com/JamorMoussa/
    # - icon: fontawesome/brands/youtube
    #   link: https://www.youtube.com/channel/UCr8O8l5cCX85Oem1d18EezQ


